---
title: "Line of Best Fit Plotting"
author: "Author Name"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(ggplot2)
library(dplyr)
```

### Import, Filter, and Mutate Data

Insert any text here.

```{r code1}
two_year <- read_csv("CollegeData_2-year.csv")
four_year <- read_csv("CollegeData_4-year.csv")
View(two_year)
View(four_year)

four_year_clean <- four_year %>%
                  select(year, inst_name, dif_white, dif_amind, dif_asian, dif_black,
                        dif_pacis, dif_twora, dif_hispa)

two_year_clean <- four_year %>%
                  select(year, inst_name, dif_white, dif_amind, dif_asian, dif_black,
                        dif_pacis, dif_twora, dif_hispa)

four_year_mag_diff <- four_year_clean %>%
                  rowwise () %>%
                  mutate(mag_diff = sum(abs(dif_white), abs(dif_hispa), abs(dif_black),
                                            abs(dif_asian), abs(dif_amind), abs(dif_pacis),
                                            abs(dif_twora), na.rm = T)) %>%
                  mutate(missing_racial_data = is.na(dif_white) + is.na(abs(dif_hispa)) 
                                              + is.na(abs(dif_black)) + is.na(abs(dif_asian)) 
                                              + is.na(abs(dif_amind)) + is.na(abs(dif_pacis))
                                              + is.na(abs(dif_twora))) %>%
                  mutate(missing_racial_data = as.character(missing_racial_data))

two_year_mag_diff <- two_year_clean %>%
                  rowwise () %>%
                  mutate(mag_diff = sum(abs(dif_white), abs(dif_hispa), abs(dif_black),
                                            abs(dif_asian), abs(dif_amind), abs(dif_pacis),
                                            abs(dif_twora), na.rm = T)) %>%
                  mutate(missing_racial_data = is.na(dif_white) + is.na(abs(dif_hispa)) 
                                              + is.na(abs(dif_black)) + is.na(abs(dif_asian)) 
                                              + is.na(abs(dif_amind)) + is.na(abs(dif_pacis))
                                              + is.na(abs(dif_twora))) %>%
                  mutate(missing_racial_data = as.character(missing_racial_data))
```


### Plotting Line of Best Fit Graphs (Diff Magnitudes)

Insert any text here.

```{r code2}

```


### Plotting Line of Best Fit Graphs (sqrt-Mean Squared Differences)

Insert any text here.

```{r code2}

```
