---
title: "Line of Best Fit Metrics"
author: "Author Name"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(ggplot2)
library(dplyr)
```

### Import, Filter, and Mutate Data

```{r code1}
two_year <- read_csv("CollegeData_2-year.csv")
four_year <- read_csv("CollegeData_4-year.csv")

four_year_clean <- four_year %>%
                  select(unitid, year, inst_name, dif_white, dif_amind, dif_asian, dif_black,
                        dif_pacis, dif_twora, dif_hispa)

two_year_clean <- two_year %>%
                  select(unitid, year, inst_name, dif_white, dif_amind, dif_asian, dif_black,
                        dif_pacis, dif_twora, dif_hispa)

#NOTE: this will take a second to complete, green bar is good!, wait until it disappears 
four_year_md_smsd <- four_year_clean %>%
                  rowwise () %>%
                  mutate(mag_diff = sum(abs(dif_white), abs(dif_hispa), abs(dif_black),
                                            abs(dif_asian), abs(dif_amind), abs(dif_pacis),
                                            abs(dif_twora), na.rm = T)) %>%
                  mutate(sse = sum((dif_white)^2, (dif_hispa)^2, (dif_black)^2, 
                              (dif_asian)^2, (dif_amind)^2, (dif_pacis)^2,
                              (dif_twora)^2, na.rm = T)) %>%
                  mutate(smsd = sqrt(1/7*sse)) %>%
                  mutate(missing_racial_data = is.na(dif_white) + is.na(abs(dif_hispa)) 
                                              + is.na(abs(dif_black)) + is.na(abs(dif_asian)) 
                                              + is.na(abs(dif_amind)) + is.na(abs(dif_pacis))
                                              + is.na(abs(dif_twora))) %>%
                  mutate(missing_racial_data = as.character(missing_racial_data))

#NOTE: this will take a second to complete, green bar is good!, wait until it disappears 
two_year_md_smsd <- two_year_clean %>%
                  rowwise () %>%
                  mutate(mag_diff = sum(abs(dif_white), abs(dif_hispa), abs(dif_black),
                                            abs(dif_asian), abs(dif_amind), abs(dif_pacis),
                                            abs(dif_twora), na.rm = T)) %>%
                  mutate(sse = sum((dif_white)^2, (dif_hispa)^2, (dif_black)^2, 
                              (dif_asian)^2, (dif_amind)^2, (dif_pacis)^2,
                              (dif_twora)^2, na.rm = T)) %>%
                  mutate(smsd = sqrt(1/7*sse)) %>%
                  mutate(missing_racial_data = is.na(dif_white) + is.na(abs(dif_hispa)) 
                                              + is.na(abs(dif_black)) + is.na(abs(dif_asian)) 
                                              + is.na(abs(dif_amind)) + is.na(abs(dif_pacis))
                                              + is.na(abs(dif_twora))) %>%
                  mutate(missing_racial_data = as.character(missing_racial_data))

###Cutting out schools with two or more years of data missing
four_year_keeper_list<- four_year_md_smsd %>%
                    group_by(unitid) %>%
                    summarize(count=n()) %>%
                    filter(count == 9 | count == 8)
two_year_keeper_list<- two_year_md_smsd %>%
                    group_by(unitid) %>%
                    summarize(count=n()) %>%
                    filter(count == 9 | count == 8)

four_year_md_cut <- four_year_md_smsd %>%
                    filter(unitid %in% four_year_keeper_list$unitid)

two_year_md_cut <- two_year_md_smsd %>%
                    filter(unitid %in% two_year_keeper_list$unitid)

length(unique(four_year_md_smsd$unitid))
length(unique(four_year_md_cut$unitid)) 

length(unique(two_year_md_smsd$unitid))
length(unique(two_year_md_cut$unitid)) 

four_year_join <- four_year_md_cut %>%
          group_by(unitid) %>%
          filter(row_number()==1)

two_year_join  <- two_year_md_cut %>%
          group_by(unitid) %>%
          filter(row_number()==1)

```

### Line of Best Fit Using Diff Magnitudes

```{r code2}
four_year_final_md <- four_year_md_cut %>%   
                  group_by(unitid) %>%
                  do(linmod = lm( mag_diff ~ year, data = .)) %>%
                  rowwise () %>%
                  mutate(slope = linmod$coefficients[2]) %>%
                  arrange(slope)

four_year_md_join <- left_join(four_year_join, four_year_final_md, by=c('unitid'='unitid')) %>%
                  select(unitid, inst_name, linmod, slope)

four_year_md_final <- four_year_md_join %>%
                    arrange(slope)

two_year_final_md <- two_year_md_cut %>%   
                  group_by(unitid) %>%
                  do(linmod = lm( mag_diff ~ year, data = .)) %>%
                  rowwise () %>%
                  mutate(slope = linmod$coefficients[2]) %>%
                  arrange(slope)

two_year_md_join <- left_join(two_year_join, two_year_final_md, by=c('unitid'='unitid')) %>%
                  select(unitid, inst_name, linmod, slope)

two_year_md_final <- two_year_md_join %>%
                    arrange(slope)
```

### Line of Best Fit Using (sqrt) Mean of Squared Differences 

```{r code3}
four_year_final_smsd <- four_year_md_cut %>%   
                     group_by(unitid) %>%
                     do(linmod = lm( smsd ~ year, data = .)) %>%
                     rowwise () %>%
                     mutate(slope = linmod$coefficients[2]) %>%
                     arrange(slope)

four_year_smsd_join <- left_join(four_join, four_year_final_smsd, by=c('unitid'='unitid')) %>%
                  select(unitid, inst_name, linmod, slope)

four_year_smsd_final <- four_year_smsd_join %>%
                    arrange(slope)

two_year_final_smsd <- two_year_md_cut %>%   
                    group_by(unitid) %>%
                    do(linmod = lm( smsd ~ year, data = .)) %>%
                    rowwise () %>%
                    mutate(slope = linmod$coefficients[2]) %>%
                    arrange(slope)

two_year_smsd_join <- left_join(two_join, two_year_final_smsd, by=c('unitid'='unitid')) %>%
                  select(unitid, inst_name, linmod, slope)

two_year_smsd_final <- two_year_smsd_join %>%
                    arrange(slope)
```

### Analysis Line of Best Fit Metrics 

```{r code3}
ggplot(four_year_final_md) +
  geom_histogram(mapping = aes(x=slope), bins = 200) +
  labs(title = "Slope Values for Line of Best Fit (Difference Magnitude) Metric \n (4-Year Colleges) (200 Bins)", 
       x= "Slope", y="Count") 

ggplot(four_year_final_smsd) +
  geom_histogram(mapping = aes(x=slope), bins = 200) +
  labs(title = "Slope Values for Line of Best Fit (Square Root of Mean of Squared Differences) \nMetric (4-Year Colleges) (200 Bins)", 
       x= "Slope", y="Count") 

ggplot(two_year_final_md) +
  geom_histogram(mapping = aes(x=slope), bins = 200) +
  labs(title = "Slope Values for Line of Best Fit (Difference Magnitude) Metric \n (2-Year Colleges) (200 Bins)", 
       x= "Slope", y="Count") 

ggplot(two_year_final_smsd) +
  geom_histogram(mapping = aes(x=slope), bins = 100) +
  labs(title = "Slope Values for Line of Best Fit (Square Root of Mean of Squared Differences) \nMetric (2-Year Colleges) (100 Bins)", 
       x= "Slope", y="Count") 
```