---
title: "Ideal Line Regression Metrics"
author: "Emily Bogle"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(ggplot2)
library(dplyr)
```

### Import, Filter, and Mutate Data

```{r code1}
two_year <- read_csv("CollegeData_2-year.csv")
four_year <- read_csv("CollegeData_4-year.csv")

four_year_clean <- four_year %>%
                  select(unitid, year, inst_name, dif_white, dif_amind, dif_asian, dif_black,
                        dif_pacis, dif_twora, dif_hispa)

two_year_clean <- four_year %>%
                  select(unitid, year, inst_name, dif_white, dif_amind, dif_asian, dif_black,
                        dif_pacis, dif_twora, dif_hispa)

#NOTE: this will take a second to complete, green bar is good!, wait until it disappears 
four_year_md_smsd <- four_year_clean %>%
                  rowwise () %>%
                  mutate(mag_diff = sum(abs(dif_white), abs(dif_hispa), abs(dif_black),
                                            abs(dif_asian), abs(dif_amind), abs(dif_pacis),
                                            abs(dif_twora), na.rm = T)) %>%
                  mutate(se = sum((dif_white)^2, (dif_hispa)^2, (dif_black)^2, 
                              (dif_asian)^2, (dif_amind)^2, (dif_pacis)^2,
                              (dif_twora)^2, na.rm = T)) %>%
                  mutate(smsd = sqrt(1/7*se)) %>%
                  mutate(missing_racial_data = is.na(dif_white) + is.na(abs(dif_hispa)) 
                                              + is.na(abs(dif_black)) + is.na(abs(dif_asian)) 
                                              + is.na(abs(dif_amind)) + is.na(abs(dif_pacis))
                                              + is.na(abs(dif_twora))) %>%
                  mutate(missing_racial_data = as.character(missing_racial_data))

#NOTE: this will take a second to complete, green bar is good!, wait until it disappears 
two_year_md_smsd <- two_year_clean %>%
                  rowwise () %>%
                  mutate(mag_diff = sum(abs(dif_white), abs(dif_hispa), abs(dif_black),
                                            abs(dif_asian), abs(dif_amind), abs(dif_pacis),
                                            abs(dif_twora), na.rm = T)) %>%
                  mutate(se = sum((dif_white)^2, (dif_hispa)^2, (dif_black)^2, 
                              (dif_asian)^2, (dif_amind)^2, (dif_pacis)^2,
                              (dif_twora)^2, na.rm = T)) %>%
                  mutate(smsd = sqrt(1/7*se)) %>%
                  mutate(missing_racial_data = is.na(dif_white) + is.na(abs(dif_hispa)) 
                                              + is.na(abs(dif_black)) + is.na(abs(dif_asian)) 
                                              + is.na(abs(dif_amind)) + is.na(abs(dif_pacis))
                                              + is.na(abs(dif_twora))) %>%
                  mutate(missing_racial_data = as.character(missing_racial_data))


```


```

